name: "Terraform"

on:
  push:
    branches:
    - main
  pull_request:
  env:
  ACCESS_KEY: ${{ secrets.ACCESS_KEY}}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Set Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
    - name: Terraform init
      run: terraform init

